### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by hongshui3000** [haneefdm/memview#1]
![image](https://user-images.githubusercontent.com/25566498/187118878-dc2303c2-9c15-4008-b6b1-b66a7383e3ed.png)

**Comment by haneefdm** [comment]
Looks like it is the download that failed. I don't think it ever got to actually installing it.

Could you try again? Just to make sure you can also download from the marketplace the VSIX file install it manually. As an experiment

**Comment by hongshui3000** [comment]
It can be installed manually, but the same error will still be output in the log，But it seems like it can be used,

**Comment by hongshui3000** [comment]
![image](https://user-images.githubusercontent.com/25566498/187125094-1aef509d-48fa-402e-b109-915213199100.png)
Cannot switch to another address

**Comment by hongshui3000** [comment]
![1661749099617](https://user-images.githubusercontent.com/25566498/187126156-dd4ff1dd-f52a-4bae-ac06-e30e3e6ace39.jpg)
How do I clear these records, I keep adding addresses and the records become unmanageable

**Comment by haneefdm** [comment]
You can delete views using the button n the far right. Do you not see that button? I am not seeing it in you screenshots. Most of the close buttons are on the right in VSCode -- pretty much everywhere. So, that is where it is right now.

Looks like the ability to switch between views is broken. Btw, a couple of those buttons on the left don't do anything yet.

**Comment by haneefdm** [comment]
I tried installing on multiple machines and OSes from the marketplace. I cannot duplicate the install/download issue.

This seems to be a VSCode issue. More than likely network/proxy issue, can happen to any extension and any OS. You may even have a corrupted VSCode install

https://github.com/Microsoft/vscode/issues/34385
https://stackoverflow.com/questions/70177216/visual-studio-code-error-while-fetching-extensions-xhr-failed
https://www.mikearthur.net/visual-studio-code-error-while-fetching-extensions-xhr-failed
https://linuxpip.org/troubleshoot-xhr-failed-on-vscode/

I am going to close this now. This is why I don't like mixing issues.

**Comment by haneefdm** [comment]
Btw, the issue with the switching between views is fixed and released. Please update the extension

**Comment by hongshui3000** [comment]
> 

![image](https://user-images.githubusercontent.com/25566498/187432100-12ce34bd-f05a-4026-8fd5-635a05fc3341.png)
I don't see any close buttons here

**Comment by haneefdm** [comment]
What version? I made an update yesterday. Since your marketplace is broken (you should report it to them) you may have to re-download it. Not sure if auto-updates are working for you

https://marketplace.visualstudio.com/items?itemName=haneefdm.memview

See also Issue #2

**Comment by hongshui3000** [comment]
![image](https://user-images.githubusercontent.com/25566498/187453431-37d99d5b-1ff6-491c-b333-4e71be9b8f97.png)

**Comment by haneefdm** [comment]
So, what happens if you use the refresh button. We are already doing a refresh. Also, when you delete one, do you see the view switch over to another one? It uses a round-robin method unless there is a set of past views you looked at.

I can't seem to duplicate this.

**Comment by haneefdm** [comment]
I think I know what is happening. We save state every time the debugger is terminated and when VSCode (or our extension) is asked to quit. Problem is, VSCode is killing our extension forcefully before we can complete saving the sate, now I am afraid that we may even be halfway done and end up with a corrupted state. So, next time you restart VSCode, a deleted item could still be in the list because it was deleted while the debugger was not running.

Saving state for every movement is out of the question. It is not cheap. Not sure what the solution is. I am now saving changes for big events like creating/deleting a new view but not for scrolling, etc. Btw, when we save state, we also remember which rows you were looking and restore that as well.

I will see what else we can do. Nothing comes to mind right now. But the next update should save state under more circumstances.
