### ISSUE TITLE
show wrong data

### ISSUE THREAD

**Issue by hongshui3000** [haneefdm/memview#5]
![image](https://user-images.githubusercontent.com/25566498/195096563-74d1f99e-ac93-48cd-a04c-5e6d5c5592ac.png)

![image](https://user-images.githubusercontent.com/25566498/195096694-f6abed5f-0f9d-45fa-bddb-b1ddca492862.png)

The data at 0x10000000 address is 0x96f3b83d, but the memview shows all 0s

**Comment by haneefdm** [comment]
Can you screenshot a bit more so I can see the status of the debugger in the memory view? There will be no fixes or changes in this repo.

BTW, in case you did not notice, we are shutting this repo down. We have moved as it will be better for the long term. See https://github.com/haneefdm/memview README.md

The new repo is https://github.com/mcu-debug/memview and it will point you to the new extension.

Sorry, but we had to move to consolidate all such extensions under an organization instead of personal.

Can you re-open the issue in the new repo please?

**Comment by hongshui3000** [comment]
https://github.com/mcu-debug/memview/issues/2
